model_name: "deit_tiny_patch16_224"
data_path: "./../data/cifar100/"
batch_size: 128
num_tasks: 10
sched: "cosine"
opt: "adam"
opt_nev: True
opt_momentum: 0.9
lr: 0.001
epochs: 15
device: "cuda:9"
has_output_adapter: True
reduction_factor: 4
has_prefix: True
prefix_length: 15
h_reg: 0.00001
bottleneck_factor: 4
l_embeddings: 64
t_embeddings: 64
print_freq: 10
validation : False
dil: False