model_name: "deit_small_patch16_224"
output_dir: "./outputs/cddb/deit_small/"
data_path: "./../data/CDDB/"
batch_size: 256
num_tasks: 10
sched: "cosine"
opt: "adam"
opt_nev: True
opt_momentum: 0.9
lr: 0.001
epochs: [5, 15, 15, 15, 15]
device: "cuda:4"
has_output_adapter: True
reduction_factor: 8
has_prefix: True
prefix_length: 15
h_reg: 0.001
bottleneck_factor: 4
l_embeddings: 64
t_embeddings: 64
print_freq: 10
validation: False
dil: True
