model_name: "vit_large_patch16_224"
data_path: "./../data/five_datasets/"
batch_size: 64
num_tasks: 10
sched: "cosine"
opt: "adam" 
opt_nev: True
opt_momentum: 0.9
lr: 0.001
epochs: 3
device: "cuda:3"
has_output_adapter: False
reduction_factor: 8
has_prefix: True
prefix_length: 15
h_reg: 0.1
bottleneck_factor: 4
l_embeddings: 64
t_embeddings: 64
print_freq: 10
validation: False
dil: False