model_name: "vit_base_patch16_224"
data_path: "./../data/"
batch_size: 128
num_tasks: 10
opt: "adam"
sched: "cosine" 
opt_nev: True
opt_momentum: 0.9
lr: 0.001
epochs: 5
device: "cuda:9"
has_atten_adapter: False
has_output_adapter: True
reduction_factor: 8
has_prefix: True
prefix_length: 15
bottleneck: 20
bottleneck_factor: 4
print_freq: 10
validation: False
